# Generated by Django 4.0.4 on 2022-06-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenTicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('setor', models.CharField(max_length=50, verbose_name='Setor')),
                ('tel_ramal', models.CharField(max_length=50, verbose_name='contato')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('dsticket', models.CharField(max_length=1500, verbose_name='dschamado')),
            ],
        ),
    ]
